aliases: []
creation_timestamp: 1704412132934
current_stage: None
description: null
last_updated_timestamp: 1704412132934
name: lr
run_id: 5c92bb01cb8241a8830258b183c384e0
run_link: null
source: /home/igor/xflow/mlflow/2/5c92bb01cb8241a8830258b183c384e0/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/5c92bb01cb8241a8830258b183c384e0/artifacts/lr
user_id: null
version: 29
