aliases: []
creation_timestamp: 1704412881974
current_stage: None
description: null
last_updated_timestamp: 1704412881974
name: lr
run_id: 786f4c10d144470b9c1941f2c0e2b606
run_link: null
source: /home/igor/xflow/mlflow/2/786f4c10d144470b9c1941f2c0e2b606/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/786f4c10d144470b9c1941f2c0e2b606/artifacts/lr
user_id: null
version: 66
