aliases: []
creation_timestamp: 1704412040217
current_stage: None
description: null
last_updated_timestamp: 1704412040217
name: lr
run_id: 14ce810ecbb44447a13628081ce97051
run_link: null
source: /home/igor/xflow/mlflow/2/14ce810ecbb44447a13628081ce97051/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/14ce810ecbb44447a13628081ce97051/artifacts/lr
user_id: null
version: 24
