aliases: []
creation_timestamp: 1704412003013
current_stage: None
description: null
last_updated_timestamp: 1704412003013
name: lr
run_id: f4ec46b2af45474489cf4faf94956afe
run_link: null
source: /home/igor/xflow/mlflow/2/f4ec46b2af45474489cf4faf94956afe/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/f4ec46b2af45474489cf4faf94956afe/artifacts/lr
user_id: null
version: 22
