aliases: []
creation_timestamp: 1704412545391
current_stage: None
description: null
last_updated_timestamp: 1704412545391
name: lr
run_id: decc54e838fd4bdc8bd4176b8f872b6c
run_link: null
source: /home/igor/xflow/mlflow/2/decc54e838fd4bdc8bd4176b8f872b6c/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/decc54e838fd4bdc8bd4176b8f872b6c/artifacts/lr
user_id: null
version: 49
