aliases: []
creation_timestamp: 1704412525137
current_stage: None
description: null
last_updated_timestamp: 1704412525137
name: lr
run_id: e0095b6e3f0f4ffd92cb61b20feaff22
run_link: null
source: /home/igor/xflow/mlflow/2/e0095b6e3f0f4ffd92cb61b20feaff22/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/e0095b6e3f0f4ffd92cb61b20feaff22/artifacts/lr
user_id: null
version: 48
