aliases: []
creation_timestamp: 1704412076356
current_stage: None
description: null
last_updated_timestamp: 1704412076356
name: lr
run_id: beac3090d832461ca861dab221699dbe
run_link: null
source: /home/igor/xflow/mlflow/2/beac3090d832461ca861dab221699dbe/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/beac3090d832461ca861dab221699dbe/artifacts/lr
user_id: null
version: 26
