aliases: []
creation_timestamp: 1704412742337
current_stage: None
description: null
last_updated_timestamp: 1704412742337
name: lr
run_id: b31095d1b8684b7f8e28d861542c4d31
run_link: null
source: /home/igor/xflow/mlflow/2/b31095d1b8684b7f8e28d861542c4d31/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/b31095d1b8684b7f8e28d861542c4d31/artifacts/lr
user_id: null
version: 59
