aliases: []
creation_timestamp: 1704412900731
current_stage: None
description: null
last_updated_timestamp: 1704412900731
name: lr
run_id: 9e9ffe9f41e148dbb125aa029b0ac22e
run_link: null
source: /home/igor/xflow/mlflow/2/9e9ffe9f41e148dbb125aa029b0ac22e/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/9e9ffe9f41e148dbb125aa029b0ac22e/artifacts/lr
user_id: null
version: 67
