aliases: []
creation_timestamp: 1704412663760
current_stage: None
description: null
last_updated_timestamp: 1704412663760
name: lr
run_id: f17d4bcb6f0a4effa13d54f732d0d88b
run_link: null
source: /home/igor/xflow/mlflow/2/f17d4bcb6f0a4effa13d54f732d0d88b/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/f17d4bcb6f0a4effa13d54f732d0d88b/artifacts/lr
user_id: null
version: 55
