aliases: []
creation_timestamp: 1704411985317
current_stage: None
description: null
last_updated_timestamp: 1704411985317
name: lr
run_id: f93a7846bb9843ff8ce5b6bf6d20fad7
run_link: null
source: /home/igor/xflow/mlflow/2/f93a7846bb9843ff8ce5b6bf6d20fad7/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/f93a7846bb9843ff8ce5b6bf6d20fad7/artifacts/lr
user_id: null
version: 21
