aliases: []
creation_timestamp: 1704411654098
current_stage: None
description: null
last_updated_timestamp: 1704411654098
name: lr
run_id: c4d4f8df29b54f069d338542e934a2ed
run_link: null
source: /home/igor/xflow/mlflow/2/c4d4f8df29b54f069d338542e934a2ed/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/c4d4f8df29b54f069d338542e934a2ed/artifacts/lr
user_id: null
version: 11
