aliases: []
creation_timestamp: 1704413131740
current_stage: None
description: null
last_updated_timestamp: 1704413131740
name: lr
run_id: 94a6dffa5ad344339bf1cbff7f023bbf
run_link: null
source: /home/igor/xflow/mlflow/2/94a6dffa5ad344339bf1cbff7f023bbf/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/94a6dffa5ad344339bf1cbff7f023bbf/artifacts/lr
user_id: null
version: 79
