aliases: []
creation_timestamp: 1704412586968
current_stage: None
description: null
last_updated_timestamp: 1704412586968
name: lr
run_id: b51a789409574a658c3067d20eced82c
run_link: null
source: /home/igor/xflow/mlflow/2/b51a789409574a658c3067d20eced82c/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/b51a789409574a658c3067d20eced82c/artifacts/lr
user_id: null
version: 51
