aliases: []
creation_timestamp: 1704411943565
current_stage: None
description: null
last_updated_timestamp: 1704411943565
name: lr
run_id: cee9dbd9eb754497b6988fb93d2c11b3
run_link: null
source: /home/igor/xflow/mlflow/2/cee9dbd9eb754497b6988fb93d2c11b3/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/cee9dbd9eb754497b6988fb93d2c11b3/artifacts/lr
user_id: null
version: 19
