aliases: []
creation_timestamp: 1704412341914
current_stage: None
description: null
last_updated_timestamp: 1704412341914
name: lr
run_id: fdc0d5b2be1642dab51c2e5a07e48046
run_link: null
source: /home/igor/xflow/mlflow/2/fdc0d5b2be1642dab51c2e5a07e48046/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/fdc0d5b2be1642dab51c2e5a07e48046/artifacts/lr
user_id: null
version: 42
