aliases: []
creation_timestamp: 1704413037652
current_stage: None
description: null
last_updated_timestamp: 1704413037652
name: lr
run_id: 2b6453eb5ba5475593c3fd21dd90fa95
run_link: null
source: /home/igor/xflow/mlflow/2/2b6453eb5ba5475593c3fd21dd90fa95/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/2b6453eb5ba5475593c3fd21dd90fa95/artifacts/lr
user_id: null
version: 74
