aliases: []
creation_timestamp: 1704411938810
current_stage: None
description: null
last_updated_timestamp: 1704411938810
name: lr
run_id: 4aa3623f9a534da2a1e107a7f20c898b
run_link: null
source: /home/igor/xflow/mlflow/2/4aa3623f9a534da2a1e107a7f20c898b/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/4aa3623f9a534da2a1e107a7f20c898b/artifacts/lr
user_id: null
version: 18
