aliases: []
creation_timestamp: 1704412722448
current_stage: None
description: null
last_updated_timestamp: 1704412722448
name: lr
run_id: f3f71b72d1284b5eb86ab42adc0b5679
run_link: null
source: /home/igor/xflow/mlflow/2/f3f71b72d1284b5eb86ab42adc0b5679/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/f3f71b72d1284b5eb86ab42adc0b5679/artifacts/lr
user_id: null
version: 58
