aliases: []
creation_timestamp: 1704413093557
current_stage: None
description: null
last_updated_timestamp: 1704413093557
name: lr
run_id: 1a57f5f4617b45fb8ca78b9df61571c9
run_link: null
source: /home/igor/xflow/mlflow/2/1a57f5f4617b45fb8ca78b9df61571c9/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/1a57f5f4617b45fb8ca78b9df61571c9/artifacts/lr
user_id: null
version: 77
