aliases: []
creation_timestamp: 1704412607169
current_stage: None
description: null
last_updated_timestamp: 1704412607169
name: lr
run_id: 792b6e28cd104e928e66fcec709b2bb3
run_link: null
source: /home/igor/xflow/mlflow/2/792b6e28cd104e928e66fcec709b2bb3/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/792b6e28cd104e928e66fcec709b2bb3/artifacts/lr
user_id: null
version: 52
