aliases: []
creation_timestamp: 1704411612707
current_stage: None
description: null
last_updated_timestamp: 1704411612707
name: lr
run_id: 6249537749144daf91cc561ba7bb3967
run_link: null
source: /home/igor/xflow/mlflow/2/6249537749144daf91cc561ba7bb3967/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/6249537749144daf91cc561ba7bb3967/artifacts/lr
user_id: null
version: 9
