aliases: []
creation_timestamp: 1704411923395
current_stage: None
description: null
last_updated_timestamp: 1704411923395
name: lr
run_id: d44021cfd0944426af8f561dd98201a4
run_link: null
source: /home/igor/xflow/mlflow/2/d44021cfd0944426af8f561dd98201a4/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/d44021cfd0944426af8f561dd98201a4/artifacts/lr
user_id: null
version: 17
