aliases: []
creation_timestamp: 1704412824898
current_stage: None
description: null
last_updated_timestamp: 1704412824898
name: lr
run_id: d0202c4963c842f39b41c198c1d0be30
run_link: null
source: /home/igor/xflow/mlflow/2/d0202c4963c842f39b41c198c1d0be30/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/d0202c4963c842f39b41c198c1d0be30/artifacts/lr
user_id: null
version: 63
