aliases: []
creation_timestamp: 1704412303183
current_stage: None
description: null
last_updated_timestamp: 1704412303183
name: lr
run_id: c68f4ed919de4a29b700a7915bcfc0cd
run_link: null
source: /home/igor/xflow/mlflow/2/c68f4ed919de4a29b700a7915bcfc0cd/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/c68f4ed919de4a29b700a7915bcfc0cd/artifacts/lr
user_id: null
version: 39
