aliases: []
creation_timestamp: 1704412919638
current_stage: None
description: null
last_updated_timestamp: 1704412919638
name: lr
run_id: 5a495ece69e9498cb0777152ead75e23
run_link: null
source: /home/igor/xflow/mlflow/2/5a495ece69e9498cb0777152ead75e23/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/5a495ece69e9498cb0777152ead75e23/artifacts/lr
user_id: null
version: 68
