aliases: []
creation_timestamp: 1704412320598
current_stage: None
description: null
last_updated_timestamp: 1704412320598
name: lr
run_id: fafae15cd4804b479513160fd10957b0
run_link: null
source: /home/igor/xflow/mlflow/2/fafae15cd4804b479513160fd10957b0/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/fafae15cd4804b479513160fd10957b0/artifacts/lr
user_id: null
version: 41
