aliases: []
creation_timestamp: 1704412979938
current_stage: None
description: null
last_updated_timestamp: 1704412979938
name: lr
run_id: cd7f19fabb7240f7aa07164d8f3af0ce
run_link: null
source: /home/igor/xflow/mlflow/2/cd7f19fabb7240f7aa07164d8f3af0ce/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/cd7f19fabb7240f7aa07164d8f3af0ce/artifacts/lr
user_id: null
version: 71
