aliases: []
creation_timestamp: 1704412505269
current_stage: None
description: null
last_updated_timestamp: 1704412505269
name: lr
run_id: b3230d1d90cf48e1a8bcbed87327761d
run_link: null
source: /home/igor/xflow/mlflow/2/b3230d1d90cf48e1a8bcbed87327761d/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/b3230d1d90cf48e1a8bcbed87327761d/artifacts/lr
user_id: null
version: 47
