aliases: []
creation_timestamp: 1704412361763
current_stage: None
description: null
last_updated_timestamp: 1704412361763
name: lr
run_id: dacb684b735044eca6c6a59f4be32df0
run_link: null
source: /home/igor/xflow/mlflow/2/dacb684b735044eca6c6a59f4be32df0/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/dacb684b735044eca6c6a59f4be32df0/artifacts/lr
user_id: null
version: 43
