aliases: []
creation_timestamp: 1704412644558
current_stage: None
description: null
last_updated_timestamp: 1704412644558
name: lr
run_id: 8b8d6fc1ca454c908db577eeae68c450
run_link: null
source: /home/igor/xflow/mlflow/2/8b8d6fc1ca454c908db577eeae68c450/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/8b8d6fc1ca454c908db577eeae68c450/artifacts/lr
user_id: null
version: 54
