aliases: []
creation_timestamp: 1704411962320
current_stage: None
description: null
last_updated_timestamp: 1704411962320
name: lr
run_id: 015bd04241b94734a576291b1ea5a2c7
run_link: null
source: /home/igor/xflow/mlflow/2/015bd04241b94734a576291b1ea5a2c7/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/015bd04241b94734a576291b1ea5a2c7/artifacts/lr
user_id: null
version: 20
