aliases: []
creation_timestamp: 1704410518751
current_stage: None
description: null
last_updated_timestamp: 1704410518751
name: lr
run_id: 09db82108b72449eb8cb5fb01321b05b
run_link: null
source: /home/igor/xflow/mlflow/2/09db82108b72449eb8cb5fb01321b05b/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/09db82108b72449eb8cb5fb01321b05b/artifacts/lr
user_id: null
version: 1
