aliases: []
creation_timestamp: 1704412805407
current_stage: None
description: null
last_updated_timestamp: 1704412805407
name: lr
run_id: 0d7b9432152b47bda5b909d0f8690194
run_link: null
source: /home/igor/xflow/mlflow/2/0d7b9432152b47bda5b909d0f8690194/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/0d7b9432152b47bda5b909d0f8690194/artifacts/lr
user_id: null
version: 62
