aliases: []
creation_timestamp: 1704410689692
current_stage: None
description: null
last_updated_timestamp: 1704410689692
name: lr
run_id: f64ec11c68c3482b987c6973836984b1
run_link: null
source: /home/igor/xflow/mlflow/2/f64ec11c68c3482b987c6973836984b1/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/f64ec11c68c3482b987c6973836984b1/artifacts/lr
user_id: null
version: 2
