aliases: []
creation_timestamp: 1704413074940
current_stage: None
description: null
last_updated_timestamp: 1704413074940
name: lr
run_id: f20538eb638a4543840b25ad7d83e9dc
run_link: null
source: /home/igor/xflow/mlflow/2/f20538eb638a4543840b25ad7d83e9dc/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/f20538eb638a4543840b25ad7d83e9dc/artifacts/lr
user_id: null
version: 76
