aliases: []
creation_timestamp: 1704411534815
current_stage: None
description: null
last_updated_timestamp: 1704411534815
name: lr
run_id: 6c4c42db60354dd3b21b140826a7fdf1
run_link: null
source: /home/igor/xflow/mlflow/2/6c4c42db60354dd3b21b140826a7fdf1/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/6c4c42db60354dd3b21b140826a7fdf1/artifacts/lr
user_id: null
version: 5
