aliases: []
creation_timestamp: 1704411692780
current_stage: None
description: null
last_updated_timestamp: 1704411692780
name: lr
run_id: 6a5cfdd39f3f466c97c3cb9c212bf752
run_link: null
source: /home/igor/xflow/mlflow/2/6a5cfdd39f3f466c97c3cb9c212bf752/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/6a5cfdd39f3f466c97c3cb9c212bf752/artifacts/lr
user_id: null
version: 13
