aliases: []
creation_timestamp: 1704412761923
current_stage: None
description: null
last_updated_timestamp: 1704412761923
name: lr
run_id: fa63ef2d81354807a1aa09b9e19b9945
run_link: null
source: /home/igor/xflow/mlflow/2/fa63ef2d81354807a1aa09b9e19b9945/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/fa63ef2d81354807a1aa09b9e19b9945/artifacts/lr
user_id: null
version: 60
