aliases: []
creation_timestamp: 1704412862273
current_stage: None
description: null
last_updated_timestamp: 1704412862273
name: lr
run_id: dc7f38e16d2a41c58790b5c41f4508e2
run_link: null
source: /home/igor/xflow/mlflow/2/dc7f38e16d2a41c58790b5c41f4508e2/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/dc7f38e16d2a41c58790b5c41f4508e2/artifacts/lr
user_id: null
version: 65
