aliases: []
creation_timestamp: 1704412702790
current_stage: None
description: null
last_updated_timestamp: 1704412702790
name: lr
run_id: 068a730c883440138c1cd7b77581fbab
run_link: null
source: /home/igor/xflow/mlflow/2/068a730c883440138c1cd7b77581fbab/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/068a730c883440138c1cd7b77581fbab/artifacts/lr
user_id: null
version: 57
