aliases: []
creation_timestamp: 1704412094725
current_stage: None
description: null
last_updated_timestamp: 1704412094725
name: lr
run_id: 77bd589e474e40e6abdd893669cbd52d
run_link: null
source: /home/igor/xflow/mlflow/2/77bd589e474e40e6abdd893669cbd52d/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/77bd589e474e40e6abdd893669cbd52d/artifacts/lr
user_id: null
version: 27
