aliases: []
creation_timestamp: 1704411553739
current_stage: None
description: null
last_updated_timestamp: 1704411553739
name: lr
run_id: c1d346c875904c0e80c64ece10cfcdf2
run_link: null
source: /home/igor/xflow/mlflow/2/c1d346c875904c0e80c64ece10cfcdf2/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/c1d346c875904c0e80c64ece10cfcdf2/artifacts/lr
user_id: null
version: 6
