aliases: []
creation_timestamp: 1704412783799
current_stage: None
description: null
last_updated_timestamp: 1704412783799
name: lr
run_id: f3a547f9cc0b45f7afa9de4ee3440b78
run_link: null
source: /home/igor/xflow/mlflow/2/f3a547f9cc0b45f7afa9de4ee3440b78/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/f3a547f9cc0b45f7afa9de4ee3440b78/artifacts/lr
user_id: null
version: 61
