aliases: []
creation_timestamp: 1704411592994
current_stage: None
description: null
last_updated_timestamp: 1704411592994
name: lr
run_id: fd9ff4fc204946348c9e60afd5470380
run_link: null
source: /home/igor/xflow/mlflow/2/fd9ff4fc204946348c9e60afd5470380/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/fd9ff4fc204946348c9e60afd5470380/artifacts/lr
user_id: null
version: 8
