aliases: []
creation_timestamp: 1704413169936
current_stage: None
description: null
last_updated_timestamp: 1704413169936
name: lr
run_id: 283bb0f78f7244248adc33abe53145fe
run_link: null
source: /home/igor/xflow/mlflow/2/283bb0f78f7244248adc33abe53145fe/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/283bb0f78f7244248adc33abe53145fe/artifacts/lr
user_id: null
version: 81
