aliases: []
creation_timestamp: 1704413151049
current_stage: None
description: null
last_updated_timestamp: 1704413151049
name: lr
run_id: c68ff21f35854764b838b50eeed82abf
run_link: null
source: /home/igor/xflow/mlflow/2/c68ff21f35854764b838b50eeed82abf/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/c68ff21f35854764b838b50eeed82abf/artifacts/lr
user_id: null
version: 80
