aliases: []
creation_timestamp: 1704412219954
current_stage: None
description: null
last_updated_timestamp: 1704412219954
name: lr
run_id: cb25f78c536e4db68c110a2fa446a3f7
run_link: null
source: /home/igor/xflow/mlflow/2/cb25f78c536e4db68c110a2fa446a3f7/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/cb25f78c536e4db68c110a2fa446a3f7/artifacts/lr
user_id: null
version: 35
