aliases: []
creation_timestamp: 1704411633392
current_stage: None
description: null
last_updated_timestamp: 1704411633392
name: lr
run_id: 4ab42e9fce89403197cba14827377ec9
run_link: null
source: /home/igor/xflow/mlflow/2/4ab42e9fce89403197cba14827377ec9/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/4ab42e9fce89403197cba14827377ec9/artifacts/lr
user_id: null
version: 10
