aliases: []
creation_timestamp: 1704411861544
current_stage: None
description: null
last_updated_timestamp: 1704411861544
name: lr
run_id: d56538c97d044660a7fa07ffe6895d12
run_link: null
source: /home/igor/xflow/mlflow/2/d56538c97d044660a7fa07ffe6895d12/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/d56538c97d044660a7fa07ffe6895d12/artifacts/lr
user_id: null
version: 15
