aliases: []
creation_timestamp: 1704412485629
current_stage: None
description: null
last_updated_timestamp: 1704412485629
name: lr
run_id: 59ccff817dba41b9a760fe2ce8a3656b
run_link: null
source: /home/igor/xflow/mlflow/2/59ccff817dba41b9a760fe2ce8a3656b/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/59ccff817dba41b9a760fe2ce8a3656b/artifacts/lr
user_id: null
version: 46
