aliases: []
creation_timestamp: 1704411516647
current_stage: None
description: null
last_updated_timestamp: 1704411516647
name: lr
run_id: 994847e679b64416abd821b6f9324d2c
run_link: null
source: /home/igor/xflow/mlflow/2/994847e679b64416abd821b6f9324d2c/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/994847e679b64416abd821b6f9324d2c/artifacts/lr
user_id: null
version: 4
