aliases: []
creation_timestamp: 1704412168224
current_stage: None
description: null
last_updated_timestamp: 1704412168224
name: lr
run_id: dd42186bf728443a930905ae61f2d4bc
run_link: null
source: /home/igor/xflow/mlflow/2/dd42186bf728443a930905ae61f2d4bc/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/dd42186bf728443a930905ae61f2d4bc/artifacts/lr
user_id: null
version: 31
