aliases: []
creation_timestamp: 1704412057800
current_stage: None
description: null
last_updated_timestamp: 1704412057800
name: lr
run_id: 96c3958fe4ba40688f2d320878e3f565
run_link: null
source: /home/igor/xflow/mlflow/2/96c3958fe4ba40688f2d320878e3f565/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/96c3958fe4ba40688f2d320878e3f565/artifacts/lr
user_id: null
version: 25
