aliases: []
creation_timestamp: 1704412206942
current_stage: None
description: null
last_updated_timestamp: 1704412206942
name: lr
run_id: d928a3ca8af0447493bcb0928559f123
run_link: null
source: /home/igor/xflow/mlflow/2/d928a3ca8af0447493bcb0928559f123/artifacts/lr
status: READY
status_message: null
storage_location: /home/igor/xflow/mlflow/2/d928a3ca8af0447493bcb0928559f123/artifacts/lr
user_id: null
version: 34
